### ISSUE TITLE
Work Period Creation automation: additional WP getting created

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#191]
When a resource Booking is created for a specific period of time, there is an additional WP created for the week before the RB Start date.

Example:
https://platform.topcoder-dev.com/taas/myteams/17244/rb/c8fc73f3-e986-48c6-9d29-57c8bf63289a
RB Dates:
04/18/2021  -  05/05/2021

Expected WPs:
WP ( Apr 18-24 , no of days: 5)
WP (Apr 25 - May 1, no of days: 5)
WP (May 02 - 08 , no of days : 2)

Actual WPs:
WP (Apr 11 -17, No of Days :0) - This is the extra WP, which should not be created
WP ( Apr 18-24 , no of days: 5)
WP (Apr 25 - May 1, no of days: 5)
WP (May 02 - 08 , no of days : 2)

cc @sandhiyakavi @maxceem @nkumar-topcoder

**Comment by maxceem** [comment]
There is one tricky moment with Work Periods. Every user should see the same WorkPeriods. But every user lives in its own timezone. So to make things clear we are calculating Work Periods in the [EDT](https://24timezones.com/time-zone/edt) timezone.

The RB start date is `2021-04-17T18:30:00.000Z` which in your timezone might be `Apr 18`. But in EDT timezone where all the Work Periods are calculated this date would be `4/17/2021, 2:30:00 PM`. That's why additional WorkPeriod is created to cover April 17.

**Comment by maxceem** [comment]
We removed timezones and time from the Resource Bookings #204, so this should be no longer an issue.

**Comment by SathyaJayabal** [comment]
Verified.
https://platform.topcoder-dev.com/taas/myteams/17283/rb/dcd926b0-374b-41e2-a7b0-70992197c571
WPs created for RB with dates (04/18/2021 -  05/05/2021)
WP ( Apr 18-24 , no of days: 5)
WP (Apr 25 - May 1, no of days: 5)
WP (May 02 - 08 , no of days : 3)

**Comment by maxceem** [comment]
Closing as it was a DEV issue only.
