### ISSUE TITLE
The Guest Email and Guest Names are not getting populated with candidate's email and name

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/taas-apis#242]
The Guest Email and Guest Names are not getting populated with candidate's email and name

example:
job: 495d82f1-59e8-477c-a826-6002e3e319b7
candidate: 98c9b0ef-6409-463d-944a-cab21da56b13

interview has been scheduled, but the candidates details not populated in the guest email and guest name fields

**Comment by urwithat** [comment]
This has been fixed.
As well as for guests not part of TC, display first part of the email in the guest name
@sandhiyakavi / @SathyaJayabal - Kindly test

**Comment by sandhiyakavi** [comment]
@urwithat The Guest Email and Guest names are getting populated now but in the Guestname field, both the userhandle and First part of the Email is getting displayed (even though the candidate is a member of Topcoder). Also now all guestnames are displayed instead of the interviewee.

![image](https://user-images.githubusercontent.com/55895538/118075111-4ff35b80-b3ea-11eb-9ecd-081cc0b5249b.png)

Mail subject has all guestnames (both userhandle and email first part) instead of only interviewee userhandle
![image](https://user-images.githubusercontent.com/55895538/118075241-921c9d00-b3ea-11eb-8222-f6255f60b68f.png)

Similarly in the Body section , 

![image](https://user-images.githubusercontent.com/55895538/118075292-b1b3c580-b3ea-11eb-81c4-0f473115f135.png)

**Comment by sandhiyakavi** [comment]
@urwithat Now in the Guestname field, only the userhandle or First part of the Email is getting displayed. But still in mail instead of the interviewee (Job candidate) all the guestnames are getting displayed.

![image](https://user-images.githubusercontent.com/55895538/118084161-31499080-b3fb-11eb-8260-fc69730d82c4.png)
![image](https://user-images.githubusercontent.com/55895538/118084220-4c1c0500-b3fb-11eb-8211-9364d760dd77.png)
![image](https://user-images.githubusercontent.com/55895538/118084255-5dfda800-b3fb-11eb-85d8-62ecfedb03e9.png)

**Comment by sandhiyakavi** [comment]
Verified in Dev Env. 

Candidate Email and name is now added to the Guest email and name field. The Email content is also displaying correctly.

![image](https://user-images.githubusercontent.com/55895538/118091840-48da4680-b406-11eb-8fe1-907460ab54bf.png)
![image](https://user-images.githubusercontent.com/55895538/118091901-5c85ad00-b406-11eb-905e-e7c83448feac.png)

![image](https://user-images.githubusercontent.com/55895538/118091570-eed98100-b405-11eb-9f41-f300433ed869.png)

**Comment by sandhiyakavi** [comment]
Verified on Prod Env

![image](https://user-images.githubusercontent.com/55895538/118446490-ab935100-b72a-11eb-8f1a-d188662bae1c.png)
