### ISSUE TITLE
Cannot get team "9050" by id

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#29]
Using our DEV API I can get a list of teams:

![image](https://user-images.githubusercontent.com/146016/100904637-e2084700-34cf-11eb-9a5b-27915ab18e05.png)

 But when I'm getting this team by id `9050`, I get an error `"Not Found"`, though I can get all other teams by id.

![image](https://user-images.githubusercontent.com/146016/100904748-ffd5ac00-34cf-11eb-9745-319e46c465bd.png)

I try with admin user `TonyJ` and with `pshah_manager` (with `bookingmanager` role).

@nkumar-topcoder do you have any idea why it could happen? This happens only for this particular team with id `9050`.

**Comment by nkumar-topcoder** [comment]
@maxceem This could because invalid data for user or skills (uuid) posted for testing purpose earlier. When app tries to pull invalid skills (skill name) to display, it's unable to fetch. Hence the error.
cannot GET /v5/skills/4ca63bb6-f515-4ab0-a6bc-c2d8531e084f (404).

Now, we have strict skills validation during Job posting. I recommend creating a new project with valid skills. The following order we have to adhere to see the valid data.

1. POST (create) a v5/project with type talent-as-a-service and get projectid.
2. GET valid v5/skills and v5/users. Note Down userid and skillsID(s)
3. POST (create) a v5/Job with ProjectID and SkillsID(s) from above. Note Down id (jobid)
4. POST (create) a v5/jobCandidate with above JobId and UserId (from point 2)
5. POST (create) v5/resourceBooking with JobId, userid and projectid, and other details. Notedown (id) resourcebooking id
6. PATCH resourcebooking as assigned

Note
- Only "assigned"  status at resourcebooking will be visible for /taas-teams/ and /taas-teams/{projectid}
- Only customer rates will be visible at the frontend.
- In TaaS context projectID = teamID

**Comment by maxceem** [comment]
Ok closing this issue as it's an issue with incorrect dev data (most likely).
