### ISSUE TITLE
[Role API] Delete end point returns Role does not exist message to some existing role

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#290]
**Steps**
Call DELETE https://api.topcoder-dev.com/v5/taas-roles/8076b36c-e557-4f65-9a46-293e7b4d58fb with an admin or booking manager token

**Current behavior** 
Returns { "message": "id: 8076b36c-e557-4f65-9a46-293e7b4d58fb \"Role\" doesn't exists."}

**Expected behavior** 
Should return code 403 and delete the role since this is an existing role which is returned by Get end point

**Comment by eisbilir** [comment]
@sdgun
This role has already been deleted from database but somehow still exists in elasticsearch index.

![resim](https://user-images.githubusercontent.com/72204071/120556663-7a42a280-c405-11eb-900a-bb779ff176d9.png)
![resim](https://user-images.githubusercontent.com/72204071/120556732-93e3ea00-c405-11eb-85a7-0119e4db53db.png)

Returns 404 when DELETE endpoint is called because it is no longer in the DB.

@nikolay83 
`taas-role` endpoint follows the same deletion logic with other endpoints and this issue seems unlikely to be reproduced.

**Comment by sdgun** [comment]
I could only recreate this with mentioned id in the description, tried with several roles but unable to reproduce.
