### ISSUE TITLE
Workperiod not getting created if RB created with Dates (through api)

### ISSUE THREAD

**Issue by sandhiyakavi** [topcoder-platform/taas-apis#321]
Description:

Workperiod not getting created if RB created with Dates (through api)

Sample RB id: c6c08ecf-9a8e-4bfc-af35-02e566646ea7, ad1e3744-635c-4483-b2fd-41af0ea22612

**Comment by maxceem** [comment]
@sandhiyakavi this has been fixed by https://github.com/topcoder-platform/taas-apis/issues/296.

QA guidelines:
- Create a RB with long duration between start/end data, like a half year or year
- It could take some time to create all the Work Periods
- Verify that all work periods has been create for that duration.

**Comment by sandhiyakavi** [comment]
Verified the issue. Created a RB with one year duration (  "startDate": "2021-06-01","endDate": "2022-06-01"). All 53 WP records got created successfully with correct content.
rb id: f1382af3-1a95-4473-b5a9-a9ee46553b35

![image](https://user-images.githubusercontent.com/55895538/121465946-83c59f00-c9f1-11eb-82b8-f99a0af44840.png)
![image](https://user-images.githubusercontent.com/55895538/121466013-a1930400-c9f1-11eb-95ab-ddb6bc202ba2.png)

2. Created another record with duration of half year.It is also working fine.
    rb id: ec01df8a-e9d1-497c-9473-59a1fa3ca715

**Comment by sandhiyakavi** [comment]
Verified on Prod Env with @nkumar-topcoder
