### ISSUE TITLE
[$50] Include  addition param key to Postevent method 

### ISSUE THREAD

**Issue by nkumar-topcoder** [topcoder-platform/taas-apis#329]
### Add additional paramater `key` for `postEvent` method for `workperiodpaymentservice`

Similar to below changes which is done for `workperiod` (for create/update)

For workperiod postevent [create](https://github.com/topcoder-platform/taas-apis/pull/325/files)
For workperiod postevent [update](https://github.com/topcoder-platform/taas-apis/pull/324/files) 

Refer only changes for `src/services/WorkPeriodService.js`, ignore changes for `src/common/helper.js`

1. Implement similar concept for  `workperiodpaymentservice` for  (create/update/delete) `postEvent`
2. Use `billing account Id` as `key`. 
3. Add joi validation for `key` at  [taas-es-processor](https://github.com/topcoder-platform/taas-es-processor/tree/feature/topic-bus-key )  for `WorkPeriodPaymentProcessorService.js`  [Example](https://github.com/topcoder-platform/taas-es-processor/pull/74/files)

lastly,
4. `workperiod` `postevent` for `delete`, the `key` is not added yet, please get the `resourcebookingid` and add the `key`.

note: use branch `feature/topic-bus-key` for both `taas-apis` and `taas-es-processor`

**Comment by maxceem** [comment]
Sum up:

**Background:**
- when we send events to Kafka, for some events we have to pass `key` so that such events would be processed inside ES Processor in correct order
- we've already done that for WorkPeriod create and update as a proof of concept https://github.com/topcoder-platform/taas-apis/pull/325/files and https://github.com/topcoder-platform/taas-apis/pull/324/files

**Task**
- now we have to add keys for other events:
- Work Period delete: also pass resource booking id as a `key` (we would have to additionally get Resource Booking to know id)
- Work Period Payment create, update and delete operation: pass `billing account id` as ` key`
- IMPROVEMENT for all keys:
   - to make it easy to understand what kind of key we pass update the value of the key like this:
     - for Resource Booking id as key, `key` must be `resource-booking-id-${resrouceBooking.id}`
     - for Billings account id as a key, `key` must be `work-period-payment-billing-account-id-${workPeriodPayment.billingAccountId}`
- Update ES Processor so ALL processors accept optional `key` in event payload, not only the events we update here. So if tomorrow we add key in some other event inside TaaS Api, ES Processor would already support it.

**Comment by xxcxy** [comment]
Judging from the current implementation, this line of code also needs to be updated.
https://github.com/topcoder-platform/tc-bus-api/blob/b41af6d01024a71b7ff3b5240b4699c6eac5468d/common/helper.js#L125

**Comment by nkumar-topcoder** [comment]
@xxcxy thanks for proactive thinking, internally team has implemented in other branch for [tc-bus](https://github.com/topcoder-platform/tc-bus-api/blob/f78fde4e72a9c85fa0b5129f999dce9485e26103/common/helper.js#L136).
It's available in `dev` tc-bus-api.

**Comment by maxceem** [comment]
@xxcxy tc-bus api is updated in the branch `feature/shapeup3`, see https://github.com/topcoder-platform/tc-bus-api/blob/feature/shapeup3/common/helper.js

@nkumar-topcoder do you think we can merge it to DEV, or not yet?

**Comment by nkumar-topcoder** [comment]
@maxceem i shall get back , it's already `deployed` to dev from other branch. You can push `key` param and verify.

**Comment by xxcxy** [comment]
From the perspective of `IMPROVEMENT for all keys`, the value of key should be an object, such as: { 'workPeriodPayment.billingAccountId': ${workPeriodPayment.billingAccountId} }, but in this verification, the key is a string

**Comment by maxceem** [comment]
@xxcxy I mean the string like this: `resourceBooking.id:${resourceBooking.id}`, not an object.

**Comment by xxcxy** [comment]
@maxceem Ok, got it.

**Comment by maxceem** [comment]
Paid via https://www.topcoder.com/challenges/4461f1d8-9602-453a-b829-aef0d07d4448

**Comment by maxceem** [comment]
This was an internal code fix and not possible to test via QA directly.
