### ISSUE TITLE
Update Notification Email Templates

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/taas-apis#476]
Update email templates as per screenshots:
- Upcoming Resource Booking Expiration  https://monosnap.com/file/ercM44QjA8rVRkKYFgAQGflLtuOYwB
- Post Interview Candidate Action Reminder https://monosnap.com/file/K0Lj5faVHLTgWMZIHPW6pMP4fweqBs
- Interview Completed https://monosnap.com/file/7ZPFtfu7X7VMg36lvAWW3Q6XxxOgdZ
- Interview Coming Up https://monosnap.com/file/4d1uu3qyc1aBY5SL66mmyWnBiKJLFE
- Candidates are available for review https://monosnap.com/file/9xqlQEYg8CNTPr0Ez1O2dP1M5xTwAg

Update subjects of the next email notifications:
- `taas.notification.job-candidate-resume-viewed`: `Topcoder -  Client View Resume for Job "{job title}"`
- `taas.notification.team-created`: `Topcoder - New Team "{team name}" Created `
- `taas.notification.job-created`: `Topcoder - New Job "{job title}" Created  in Team "{team name}"`
- `taas.notification.job-candidate-selected`: `Topcoder - Job Candidate "{user handle}" Selected  for "{job title}" in Team "{team name}"`
- `taas.notification.resource-booking-placed`: `Topcoder - Resource Booking "{user handle}" Placed for Job "{job title}" in Team "{team name}"`

**Comment by maxceem** [comment]
@tejad paid via https://www.topcoder.com/challenges/79139c7c-0f6a-479c-bef1-44cd17003fde

**Comment by sdgun** [comment]
Verified in Dev and following issues exist; couldn't verify Candidates are available for review and Post Interview Candidate Action Reminder  templates due to https://github.com/topcoder-platform/taas-apis/issues/515, https://github.com/topcoder-platform/taas-apis/issues/505

**Interview coming up:**

Expected:
![image](https://user-images.githubusercontent.com/4592712/130193175-ba520adb-48b6-48ff-9cc6-1737ff5fcfb7.png)

Actual:
The changes requested in this ticket(as in above image) are not addressed

![image](https://user-images.githubusercontent.com/4592712/130193304-afc2eb5c-d37d-4ec1-9c10-e219f17f7de7.png)


**Interview Completed:**
Expected:
![image](https://user-images.githubusercontent.com/4592712/130193614-e74b2f1a-fb4a-4d75-984c-99d22f15d9b0.png)

Actual:
The changes requested in this ticket(as in above image) are not addressed
![image](https://user-images.githubusercontent.com/4592712/130193652-beb0c4d1-f5a4-4067-8193-6bae84dfd9cf.png)

**Upcoming Resource Booking Expiration:**
Expected:
![image](https://user-images.githubusercontent.com/4592712/130193960-519625c9-e7c4-4342-829c-839ff14cfe28.png)

Actual:
The changes requested in this ticket(as in above image) are not addressed
![image](https://user-images.githubusercontent.com/4592712/130194022-3eecb57a-339a-4757-b01c-9dfa1e451a30.png)

**Comment by maxceem** [comment]
@sdgun this should be fixed now, email template has been updated.

**Comment by sdgun** [comment]
Verified in Dev.
