### ISSUE TITLE
Long load times for taas-teams/:id/jobs/:id

### ISSUE THREAD

**Issue by wdprice** [topcoder-platform/taas-apis#50]
Long running API call, presumably due to ubahn API calls. Need to review the structure of the calls to ubahn APIs.

![image](https://user-images.githubusercontent.com/6014049/101540503-1a939f00-396e-11eb-92b4-26641d1314af.png)

**Comment by wdprice** [comment]
@nkumar-topcoder - it may be worth reviewing the API calls with @callmekatootie to see if we're leveraging the elsatic.co implementation in ubahn effectively.

**Comment by callmekatootie** [comment]
At [this](https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/TeamService.js#L246) line, when you fetch the user's details, you could pass the query param `enrich` with a value of `true`. This will give you the user's details as well as the skill.

Thus, at [this line](https://github.com/topcoder-platform/taas-apis/blob/dev/src/services/TeamService.js#L266) you no longer have to fetch the individual user's skills once again - because in the earlier step, you would already have received it.

Basically, instead of the existing api call which is: `/v5/users/:userId` - call `/v5/users/:userId?enrich=true` - and that will give you the skills too. 1 single api call instead of two.

This comes at a cost of increased payload size - and hence I am not sure how much it will improve the response time but does not hurt to test this approach and verify if there is any change in improvement to the previous response time.

(Don't forget to capture the response time before and after your changes - to measure improvement)

**Comment by maxceem** [comment]
Thank you, @callmekatootie your advice helped a LOT! Loading time has been reduced from **~20 seconds** to **~1 second**. Huge performance gain.

**Comment by maxceem** [comment]
Done via commits 1998370272ed2d8bbbb9d65ee0d06cb68d224826 and 91c98df98d28b04ba3d658c9f8a2dfbba1f2dba9.

**Comment by maxceem** [comment]
This is fixed and works good, so I'm closing it.
FYI @nkumar-topcoder
