### ISSUE TITLE
Zoom meeting is set to a recurring meeting

### ISSUE THREAD

**Issue by sdgun** [topcoder-platform/taas-apis#612]
When joing meetings as customer and JC from the links sent in the emails, noticed the meeting is set to a recurring meeting even though there is only one occurance.

![image](https://user-images.githubusercontent.com/4592712/140037033-a97414e0-211d-4bcb-99c8-b6b4f6d80ef5.png)

**Comment by maxceem** [comment]
# Topcoder TaaS Interview - Zoom Links

## Context

### Project Context

TaaS (Talent as a Service) is Topcoder project which lets customers hire top freelancers for gigs and directly manage the talents.

### Challenge Context

When customers want to hire freelancers from Topcoder, Topcoder would prepare a list of **Job Candidates** who are suitable for customer requirements. Customers could select any **Job Candidate** from the list and schedule an interview in Zoom with such a **Job Candidate**, see [screenshot](https://monosnap.com/file/aYq3UbjMbxLySAsrneKrSDCEKZPedN).

At the moment the whole workflow is already implemented and both **Customer** and **Job Candidates** (JC) got Zoom links for the meeting. But there are 2 big issues with the current Zoom links:
- zoom links using allow Customer and JC to have a meeting any time, which is not good, as we use the same Zoom account for many meetings, and we want to make sure, that it only used during the time of scheduled interview
-  we send a special "host" link to the Customer which allows Customers to start the meeting, but this link expires in 2 hours

In this challenge, we have to 

## Expected Outcome

Update the way how we generate Zoom links:
- zoom links should be created for a specific time
- instead of directly sending short-lasting zoom links, send long-lasting Topcoder API links which would redirect to Zoom links

## Challenge Details

### Technology Stack

- Node.js
- PostgreSQL
- ElasticSearch
- [Nylas](https://www.nylas.com/)

### Code access

The work would be done in 1 repository

- https://github.com/topcoder-platform/taas-apis branch **feature/interview-zoom-links**

Guide on how to setup the current code locally is shared on the forum.

### Individual requirements



### Deployment and Verification Guide

Provide a deployment and verification guide which reviewers can follow to setup code locally and steps to verify it.

### General requirements

- Existent unit tests should pass.
- Lint should pass.

## Scorecard Aid

- Submission should be evaluated as per scorecard.
- Code quality is important to us too and it has to be evaluated in the corresponding sections of the scorecard.

## What To Submit

- Submit a zip file which would include:
  - a [Git patch](https://stackoverflow.com/questions/5159185/create-a-git-patch-from-the-uncommitted-changes-in-the-current-working-directory) with changes you’ve made to the code in our repositories.
  - deployment and verification guide.
- Additionally, the winner would be required to raise a pull request to the repositories after the challenge is completed.

**Comment by sdgun** [comment]
Verified in Dev env

![image](https://user-images.githubusercontent.com/4592712/146870078-104a9738-d05d-4725-a25d-6272dc125ad1.png)

**Comment by sdgun** [comment]
Verified in production, it's passing.
